### ISSUE TITLE
Fast font doesn't work on Kobo reader.

### ISSUE THREAD

**Issue by pingdude** [Born2Root/Fast-Font#1]
The font turned on plain sans and serif on Kobo e-reader. It can display BR font epubfiles converted by the BR webapp. Something might be off.

**Comment by Born2Root** [comment]
With the font you don't need to convert your files with BR webapp anymore.
The font does the same, but without any converting hassle direct in realtime.

Try just uploading the font as a custom font on your Kobo device. Use a standard epub (not a preconverted BR one)
If it still does not work it might be, that the Kobo-Reader does not support Open-Type Font Features.
Or if it supports them, they have to be activated manually somewhere in the settings.
Since I dont have a Kobo I can't test it...

**Comment by kafujo** [comment]
Fast Font DOES work on Kobo reader, but only if you use the KoReader extension (it doesn't get recognized in vanilla Kobo). Here is proof of it working on a Kobo in KoReader, and a link to a Reddit thread with instructions:

https://www.reddit.com/r/kobo/comments/186y8m7/speedreading_bionic_font_fast_font_working_on/

![IMG_20231129_112326774 (1)](https://github.com/Born2Root/Fast-Font/assets/149900376/9d81c868-5fae-4a88-8820-9d7c64959391)
