### ISSUE TITLE
Python script

### ISSUE THREAD

**Issue by yonatankremer** [Born2Root/Fast-Font#11]
There's a python script mentioned in the readme, but it isn't anywhere in the repo. I'd like to play with the fast fonts, but it's a little too much work for... well, a font. Seems like you already have a fast-bookerly, would love to try it.

**Comment by Born2Root** [comment]
The Python-Script is mentionend and linked in the README.md
You can find the script on [Simon Cozens Github](https://github.com/simoncozens/test-fonts/blob/master/addfeatures.py)

Well at the beginning I thought the same about the effort, but while going down that Font-OpenType programming rabbithole I realized that it is a real interesting playground 😁
So my hint is, start playing around, the possibilities are pretty cool.
There are some links for starting out mentioned at the end of the [README.](https://github.com/Born2Root/Fast-Font?tab=readme-ov-file#useful-links)

Yes try the Fast-Serif out, if you want a Bookerly like experience.
It is not hundred percent the Bookerly font, because that is proprietary from Amazon and unfortunately not open-source.
Still for me the experience is pretty close...
