### ISSUE TITLE
Kindle compatibilty

### ISSUE THREAD

**Issue by arcanite24** [Born2Root/Fast-Font#8]
Hi!

Is this compatible with Kindle?

I'm putting the .ttf files into the /fonts directory and they're not showing up

**Comment by Born2Root** [comment]
Hi,

I have no Kindle so I cannot check it out myself, but I know it works on Kobo-Reader.

Still I looked it up on the internet.
As far as I understood the Kindle needs 4 font-variants of the same font, be placed in the folder.

The official info is:
```
Note: In order for the Kindle to recognize which style the font has, the fonts must comply with these conventions:
    Fontname-Regular.ttf (normal)
    Fontname-Italic.ttf (italic)
    Fontname-Bold.ttf (bold)
    Fontname-BoldItalic.ttf (bold and italic)

If the font is copied to the device and does not correspond to this naming scheme, the Kindle will not recognize it.
```
This means you first of all have to name the font like "Fastfont-Regular.ttf".
I also read somewhere that the kindle (dependend on the firmware version) needs exactly this 4 names.
Since we have Regular and Bold combined in the FastFont you have to copy the Font four times and name it differently - Regular, -Italic, -Bold and -BoldItalic like mentioned above.

Afterwards the Kindle should at least show you the font in the selection menu.
You have to try out if the speed-reading functionality works. That is dependend on, if the kindle supports the opentype features of the font, that are the intelligence to print certain letters bold for speed-reading.

It would be great if you could post a short comment, if it worked or not.
That could help other users trying the same ;-)

**Comment by arcanite24** [comment]
Thanks for your response!

I'll definitely try adding the 4 variants.

Some interesting findings I made last week:

- The two regular files work out of the box on Kindle but only with DRM books, in this case, those purchased directly on the Amazon store.
- Local books pushed to the Kindle via Calibre doesn't allow the font change
- Removing the DRM or converting them to AZW3/Mobi unlock the font change feature
- "Baking" the font in Calibre editor doesn't work too, Kindle overrides it

Hopefully I can find a solution and open up a PR with the fix

Thanks for the amazing work, I've been reading waaay faster and I can understand a lot more than before

**Comment by maciejmrowiec** [comment]
I can verify that the font worked straight out of the box with Kindle Paperwhite (5th gen) by copying `Fast-sans.ttf` and `Fast-serif.ttf` as they are.

**Comment by arcanite24** [comment]
Same @GoSuToSaKuRa 

It works great with books purchased directly from Amazon.

For books sent via Calibre:
- MOBI files doesn't show the fonts
- AZW3 files, show the fonts, but it doesn't have the effect, looks like a regular font

**Comment by arcanite24** [comment]
I just created a Python script that applies this effect directly to the files:
https://github.com/arcanite24/libre-bioread

**Comment by echarrod** [comment]
Can confirm this works out the box for me too, copying the two files (`Fast-sans.ttf` and `Fast-serif.ttf`) over to my Kindle Paperwhite 6" 👌 Thanks!

**Comment by giutala** [comment]
I made a python script that reads the books in your Calibre, let's you choose which ones to convert, and runs @arcanite24 script automatically: https://github.com/giutala/calibre_bionic_converter

**Comment by mariocornejo3** [comment]
Just uploaded the for files with the names you posted and it worked with Calibre loaded epubs without any issue!

**Comment by wwwstalkerwww** [comment]
Hi, am I right to understand that it is impossible to use this font without converting books with a script?
Amazon Kindle Paperwhite 7th Gen
With books downloaded from the store everything works. Books downloaded through Calibre do not display the font. Is there no solution to this problem?

**Comment by SokolUA19** [comment]
Will this font be supported on the BOOK Go 6 e-reader? I tried adding this font, the system recognizes it, and I can even change the interface font, but when opening a book, it does not display correctly and looks like a regular font. Thank you for your response! P.S. The language I read in is Ukrainian.

**Comment by lukdva** [comment]
- Kindle paperwhite
- Kindle 5.12.5
- Calibre 5.38

I had same issue where `.azw3` did display bionic font options to apply on kindle, however, didn't apply boldness for letters once selected.
Converting files to `.kfx` resolved it.
Though, this required installing:
- KFX Output plugin for calibre
- Kindle Previewer 3.102.0

**Comment by Danny261** [comment]
I got it to work by doing following:

1. follow all steps on how to put the fonts on your kindle
2. download the KFX output plugin from the calibre plugin store.
3. download the kindle previewer 3 from amazon or else the conversion will fail.
4. convert your book to KFX 
5. sideload it via calibre
6. select the font you previously put into the font folder
